corpusDir: './corpus/calldata/'
testMode: assertion
coverage: true
solcArgs: "--evm-version cancun --optimize-runs 200 --via-ir"
testLimit: 100000
shrinkLimit: 10000
propMaxGas: 0xffffffffffffffff
testMaxGas: 0xffffffffffffffff
